type = "fragment"

[custom_settings.minion_like.waveform]
waveform_values = [ 0, 5, 5, 5, 10, 10, 15, 15, 15, 20, 20, 25, 25,
                    25, 30, 30, 25, 25, 25, 20, 20, 15, 15, 15, 10,
                    10, 5, 5, 5, 0, 0, -5, -5, -5, -10, -10, -15, -15,
                    -15, -20, -20, -25, -25, -25, -30, -30, -25, -25,
                    -25, -20, -20, -15, -15, -15, -10, -10, -5, -5, -5,
                    0 ]
